lintAnsTest:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: ['']
  variables:
    CI_REGISTRY: 'it-docker.deltaww.com'
    CI_REGISTRY_USER: 'docker.itmdev'
    CI_REGISTRY_PASSWORD: 'QqIlB1NoZeDjwrpQ'
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfiles/LintAndTestDockerfile" --no-push
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: ['']
  variables:
    CI_REGISTRY: 'it-docker.deltaww.com'
    CI_REGISTRY_USER: 'docker.itmdev'
    CI_REGISTRY_PASSWORD: 'QqIlB1NoZeDjwrpQ'
  script:
    - DATE=`date '+%Y%m%d.%H%M%S'`
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfiles/Dockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_NAME}:$DATE-${CI_COMMIT_SHA:0:8}"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
buildStage:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: ['']
  variables:
    CI_REGISTRY: 'it-docker.deltaww.com'
    CI_REGISTRY_USER: 'docker.itmdev'
    CI_REGISTRY_PASSWORD: 'QqIlB1NoZeDjwrpQ'
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfiles/BuildStageDockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_NAME}-builder"
  only:
    changes:
      - package.json
testRunner:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: ['']
  variables:
    CI_REGISTRY: 'it-docker.deltaww.com'
    CI_REGISTRY_USER: 'docker.itmdev'
    CI_REGISTRY_PASSWORD: 'QqIlB1NoZeDjwrpQ'
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfiles/TestRunnerDockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_NAME}-test-runner"
  when: manual